services:
  web:
    image: nikolaik/python-nodejs:python3.11-nodejs20-slim
    working_dir: /w
    volumes:
      - .:/w
      - /w/theme/static_src/node_modules/
      - /w/app/migrations/
    command: >
      sh -c " pip install django-tailwind django-widget-tweaks django-environ django-browser-reload django-jazzmin
              npm i -C theme/static_src/
              rm db.sqlite3
              [ ! -f ".env" ] && cp .env-example .env
              ./manage.py makemigrations app
              ./manage.py migrate
              ./manage.py tailwind build
              ./manage.py tailwind start & ./manage.py runserver 0.0.0.0:8000
              "
    ports:
      - 8000:8000